DROP SCHEMA IF EXISTS `yunoceandb` ;

-- -----------------------------------------------------
-- Schema base
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yunoceandb` DEFAULT CHARACTER SET utf8 ;

USE yunoceandb;

	
DROP TABLE IF EXISTS ENTERPRISE;
CREATE TABLE ENTERPRISE (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CREATE_TIME` TIMESTAMP DEFAULT NOW() COMMENT '创建时间',
  `UPDATE_TIME` TIMESTAMP DEFAULT NOW() COMMENT '更新时间',
  `CREATE_ID` BIGINT(20) DEFAULT NULL COMMENT '创建者的用户ID',
  `UPDATE_ID` BIGINT(20) DEFAULT NULL COMMENT '更新者的用户ID',  
  `NAME` varchar(256) DEFAULT NULL COMMENT '企业名称',
  `ADDRESS` varchar(256) DEFAULT NULL COMMENT '详细地址',
  `PHONE` varchar(64) DEFAULT NULL COMMENT '联系电话',
  `TELEPHONE` varchar(45) DEFAULT NULL COMMENT '固定电话或座机或传真',
  `MEMBERSHIP` varchar(128) DEFAULT NULL COMMENT '会员身份',
  `BUSI_YEARS` SMALLINT(2) DEFAULT NULL COMMENT '营业年限，3年以内，5年以内，10年以内，10年以上',
  `ESIZE` SMALLINT(2) DEFAULT NULL COMMENT '企业规模，枚举定义  100人以下，100到300人，300到500人，500人以上',
  `MAIN_BUSI` varchar(256) DEFAULT NULL COMMENT '主营业务',
  `URL` varchar(128) DEFAULT NULL COMMENT '网址',  
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='企业表';

-- 权限
DROP TABLE IF EXISTS `PERMISSIONS`;
CREATE TABLE `PERMISSIONS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CREATE_TIME` TIMESTAMP DEFAULT NOW() COMMENT '创建时间',
  `UPDATE_TIME` TIMESTAMP DEFAULT NOW() COMMENT '更新时间',
  `CREATE_ID` BIGINT(20) DEFAULT NULL COMMENT '创建者的用户ID',
  `UPDATE_ID` BIGINT(20) DEFAULT NULL COMMENT '更新者的用户ID',  
  `DESCRIPTION` varchar(255) DEFAULT NULL COMMENT '描述',
  `NAME` varchar(255) NOT NULL COMMENT '权限的名称',    
  `PARENT_ID` BIGINT(20) DEFAULT NULL COMMENT '上级的ID',
  `PARENT_IDS` varchar(255) DEFAULT NULL COMMENT '上级的ID的id组，如：1,20,30',
  `PERMISSION` varchar(255) DEFAULT NULL COMMENT '权限：userInfo:list  或  userInfo:add 或  userInfo:del',
  `RESOURCE_TYPE` INT(11) DEFAULT 0 COMMENT '资源的类型 0 根菜单   1 一级菜单   2 2级菜单       100 按钮',
  `DISPLAY` TINYINT(1) DEFAULT 1 COMMENT '是否不显示   1 显示  0 隐藏',
  `SORT` INT(11) DEFAULT NULL COMMENT '排序，根据RESOURCE_TYPE按类别排序',
  `ICON` varchar(100) DEFAULT NULL COMMENT '菜单的图标',
  `INTERNAL_OR_EXTERNAL` TINYINT(1) DEFAULT 0 COMMENT '外链菜单打开方式 0/内部打开 1/外部打开',
  `URL` varchar(255) DEFAULT NULL COMMENT '如：userInfo/userView',
  PRIMARY KEY (`ID`)  
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='权限表';



-- 管理用户表
DROP TABLE IF EXISTS E_USER;
CREATE TABLE E_USER (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `PARENT_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '直属上级id',
  `ENTERPRISE_ID` BIGINT(20) NULL DEFAULT 1 COMMENT '所归属的企业ID',
  `CREATE_TIME` TIMESTAMP DEFAULT NOW() COMMENT '创建时间',
  `UPDATE_TIME` TIMESTAMP DEFAULT NOW() COMMENT '更新时间',
  `CREATE_ID` BIGINT(20) DEFAULT NULL COMMENT '创建者的用户ID',
  `UPDATE_ID` BIGINT(20) DEFAULT NULL COMMENT '更新者的用户ID',  
  `USERNAME` varchar(255) DEFAULT NULL UNIQUE COMMENT '用户名的登录名称',
  `PASSWORD` varchar(255) DEFAULT NULL COMMENT '密码',
  `NICKNAME` varchar(64) DEFAULT NULL COMMENT '昵称',
  `REALNAME` varchar(64) DEFAULT NULL COMMENT '用户真实名称',
  `DESCRIPTION` varchar(256) DEFAULT NULL COMMENT '描述',
  `SEX` tinyint(1) DEFAULT '1' COMMENT '0 男   1 女  默认 1',
  `AGE` SMALLINT(2) DEFAULT NULL COMMENT '年龄',
  `JOB_NUMBER` varchar(32) DEFAULT NULL COMMENT '工号',
  `PHONE` varchar(64) DEFAULT NULL COMMENT '电话号码',
  `TELEPHONE` varchar(45) DEFAULT NULL COMMENT '固定电话或座机',
  `IDENTITY_CARD` varchar(20) DEFAULT NULL COMMENT '身份证',
  `ADDRESS` varchar(255) DEFAULT NULL COMMENT '地址',  
  `ONLINE` tinyint(4) DEFAULT '0' COMMENT '0 登出状态    1 登录状态',
  `QQ` varchar(32) DEFAULT NULL COMMENT 'QQ号码',  
  `LEVEL` TINYINT DEFAULT 10 COMMENT '级别,等级  1 系统级用户   10 企业级用户 ',  
  `EMAIL` varchar(32) DEFAULT NULL COMMENT '邮箱',  
  `STATUS` TINYINT DEFAULT 0 COMMENT '0 离职  对离职用户，将用户名修改为 姓名+ 离职   , 1 在职 ',
  `VERSION` INT(11) NULL DEFAULT 1 COMMENT '版本',
  `DELETED` TINYINT NULL DEFAULT 0 COMMENT '逻辑删除标识（0，未删除；1，已删除）',
  `REMARK` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='企业用户表';

ALTER TABLE E_USER ADD INDEX ENTERPRISE_ID_INDEX(ENTERPRISE_ID);

INSERT INTO `e_user` (`ID`, `PARENT_ID`, `ENTERPRISE_ID`, `CREATE_TIME`, `UPDATE_TIME`, `USERNAME`, `PASSWORD`, `NICKNAME`, `REALNAME`, `DESCRIPTION`, `SEX`, `AGE`, `JOB_NUMBER`, `PHONE`, `TELEPHONE`, `IDENTITY_CARD`, `ADDRESS`, `ONLINE`, `QQ`, `LEVEL`, `EMAIL`, `STATUS`, `VERSION`, `DELETED`, `REMARK`) VALUES
	(1, 0, 0, '2020-01-06 16:26:41', '2020-01-06 16:26:41', 'admin', '6b9a6184544f456fdedecbab37c6f4ed98724a758b766482ed3c25bbc73eb900', 'admin', 'admin', NULL, 1, 100, NULL, '13600000000', NULL, NULL, NULL, 0, NULL, 1, NULL, 0, 1, 0, NULL);


-- 角色
DROP TABLE IF EXISTS `E_ROLE`;
CREATE TABLE `E_ROLE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CREATE_TIME` TIMESTAMP DEFAULT NOW() COMMENT '创建时间',
  `UPDATE_TIME` TIMESTAMP DEFAULT NOW() COMMENT '更新时间',
  `CREATE_ID` BIGINT(20) DEFAULT NULL COMMENT '创建者的用户ID',
  `UPDATE_ID` BIGINT(20) DEFAULT NULL COMMENT '更新者的用户ID',  
  `ENTERPRISE_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '所归属的企业ID',
  `DESCRIPTION` varchar(256) DEFAULT NULL COMMENT '描述',
  `NAME` varchar(64) NOT NULL COMMENT '角色的名称',  
  PRIMARY KEY (`ID`),
  UNIQUE KEY `NAME_UNIQUE` (`NAME`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8mb4 COMMENT='用户角色表';

-- 用户和角色的对应关系 用户与角色1对多关系
DROP TABLE IF EXISTS `E_USER_ROLE`;
CREATE TABLE `E_USER_ROLE` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CREATE_TIME` TIMESTAMP DEFAULT NOW() COMMENT '创建时间',
  `UPDATE_TIME` TIMESTAMP DEFAULT NOW() COMMENT '更新时间',
  `CREATE_ID` BIGINT(20) DEFAULT NULL COMMENT '创建者的用户ID',
  `UPDATE_ID` BIGINT(20) DEFAULT NULL COMMENT '更新者的用户ID',  
  `ENTERPRISE_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '所归属的企业ID',
  `USER_ID` BIGINT(20) NOT NULL COMMENT '对应的用户ID',
  `ROLE_ID` BIGINT(20) NOT NULL COMMENT '对应的角色ID',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户与角色的对应关系表，支持用户与角色多对多关系';

ALTER TABLE E_USER_ROLE ADD INDEX USER_ID_INDEX(USER_ID);

-- 权限对应角色
DROP TABLE IF EXISTS `E_ROLE_PERMISSIONS`;
CREATE TABLE `E_ROLE_PERMISSIONS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CREATE_TIME` TIMESTAMP DEFAULT NOW() COMMENT '创建时间',
  `UPDATE_TIME` TIMESTAMP DEFAULT NOW() COMMENT '更新时间',
  `CREATE_ID` BIGINT(20) DEFAULT NULL COMMENT '创建者的用户ID',
  `UPDATE_ID` BIGINT(20) DEFAULT NULL COMMENT '更新者的用户ID',  
  `ENTERPRISE_ID` BIGINT(20) NULL DEFAULT NULL COMMENT '所归属的企业ID',
  `ROLE_ID` BIGINT(20) NOT NULL COMMENT '归属角色的ID',
  `PERMISSIONS_ID` BIGINT(20) NOT NULL COMMENT '归属权限的ID',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色权限对应表 角色与权限 多对多关系';

ALTER TABLE E_ROLE_PERMISSIONS ADD INDEX ROLE_ID_INDEX(ROLE_ID);
































