server:
   port: 9999
   tomcat:
      max-swallow-size: -1
   servlet:
      context-path: /
   compression:
      enabled: true
      min-response-size: 1024
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

spring:
   servlet:
     multipart:
        max-file-size: 100MB
        max-request-size: 10MB
   datasource:   
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      #driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: huluwa@&*(.QWE
      #url: jdbc:mysql://localhost:3306/test?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      url: jdbc:p6spy:mysql://localhost:3306/yunoceandb?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      druid:
         #2.连接池配置
         #初始化连接池的连接数量 大小，最小，最大
         initial-size: 5
         min-idle: 5
         max-active: 200
         #配置获取连接等待超时的时间
         max-wait: 60000
         #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
         time-between-eviction-runs-millis: 60000
         # 配置一个连接在池中最小生存的时间，单位是毫秒
         min-evictable-idle-time-millis: 30000
         validation-query: SELECT 1 FROM DUAL
         test-while-idle: true
         test-on-borrow: true
         test-on-return: false
         # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
         pool-prepared-statements: true
         max-pool-prepared-statement-per-connection-size: 20
         # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
         filter:
            stat:
               merge-sql: true
               slow-sql-millis: 5000
         #3.基础监控配置
         web-stat-filter:
            enabled: true
            url-pattern: /*
            #设置不统计哪些URL
            exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
            session-stat-enable: true
            session-stat-max-count: 100
            stat-view-servlet:
               enabled: true
               url-pattern: /druid/*
               reset-enable: true
               #设置监控页面的登录名和密码
               login-username: admin
               login-password: admin
               allow: 127.0.0.1
               #deny: 192.168.1.100
   redis:
      # password: yunocean123   
      lettuce:
         pool:
            max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
            max-idle: 10 # 连接池中的最大空闲连接
            min-idle: 5 # 连接池中的最小空闲连接            
            max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
         shutdown-timeout: 100ms
      #sentinel:  哨兵模式
      cluster:
         nodes:
         - 192.168.1.5:5980
         - 192.168.1.5:5981
         - 192.168.1.5:5982
         - 192.168.1.5:5983
         - 192.168.1.5:5984
         - 192.168.1.5:5985
         master: mymaster
         max-redirects: 3 # 获取失败 最大重定向次数
      timeout: 8000 #客户端超时时间单位是毫秒 默认是2000
   messages: 
      encoding: UTF-8
      basename: i18n/messages
logging:
   level:        
      com.yunocean.base.dao: trace # SQL日志输入
      #config: classpath:logback-spring.xml
      #path: D:/nmyslog/nmys
   pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss} %p [%c{1}:%L]%X{insignia} - %m%n'
mybatis-plus:
   mapper-locations: mapper/*.xml
   global-config:      
      banner: false  # 关闭MP3.0自带的banner
      db-config:
         # 主键策略
         id-type: auto
         # 表名前缀
         #table-prefix: t
         # 表名是否使用下划线间隔，默认：是
         table-underline: true
         #logic-not-delete-value: 0
         #logic-delete-value: 1
# 添加mybatis配置文件路径
# config-location: mybatis-config.xml
# 配置实体类包地址
   #type-aliases-package: com.yunocean.base.model
# 驼峰转下划线
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true
      
yunocean:
   permissions:
      scanpath: com.yunocean.base.controller #多个包逗号隔开